- libs/platforms/rosa/hypershift/hypershift.py
- libs/platforms/rosa/rosa.py
- libs/utils.py
- rosa-burner.py
Capture Ctrl-C so wrapper wont be killed and will stop installing clusters, letting running install to finish and delete everything before exiting
- Closes #
> Capture Ctrl-C key during the execution

- libs/platforms/platform.py
- libs/platforms/rosa/hypershift/hypershift.py
- libs/utils.py
Scrape and index mgmt cluster metrics during creation of HCs
PR - https://github.com/cloud-bulldozer/e2e-benchmarking/pull/638 
- Closes #
> index MC metrics during creation phase

- libs/utils.py
When executing the cluster_create command, as we are using a log file to dump the output, on execution failures we are loosing the output, this commit will dump the content of the log file to avoid errors like this:
2023-11-23 10:57:54,709 ERROR utils - subprocess_exec: Failed to execute command: rosa create cluster --cluster-name rbur-ls8-0001 --replicas 3 --hosted-cp --sts --mode auto -y --output json --oidc-config-id xxxx --properties provision_shard_id:xxxx
2023-11-23 10:57:54,710 ERROR utils - subprocess_exec: 
2023-11-23 10:57:54,710 ERROR utils - subprocess_exec: 
2023-11-23 10:57:54,710 DEBUG hypershift - create_cluster: None
2023-11-23 10:57:54,710 DEBUG hypershift - create_cluster: None
- Closes #
> dump log file when there is any error executing a subcommand

- libs/platforms/rosa/hypershift/hypershift.py
Automation is failing on the create command because VPC subnets are not being detected:
E: Failed to get the list of subnets: InvalidSubnetID.NotFound: The subnet ID 'subnet-007d1ec0d50c4b125' does not exist
status code: 400, request id: 908c1f08-e20d-4b92-aaf5-af657c0db2b1
Adding --region AWS_REGION seems to fix the problem, it is like a requirement on the last rosa cli version
- Closes #
> Add --region parameter to rosa create command, without it, it cannot find the vpc subnets

- libs/platforms/rosa/hypershift/hypershift.py
- libs/platforms/rosa/terraform/terraform.py
to timestamp the graph when the control planes are ready this way we can observe any delays between cluster creations that represents the scheduling delays as well
Pin the graph when the control planes are ready, this way we can observe any delays between cluster creations especially the MC scheduling delays.
Currently it timestamps after worker ready.
- Closes #
> setting the index timestamp

- .github/workflows/tests.yml
We need to first update the CI so [PR](https://github.com/cloud-bulldozer/rosa-burner/pull/24) for renaming will use it 
- Closes #
> Adapt CI to new name of the wrapper

- Dockerfile
- libs/aws.py
- libs/platforms/rosa/rosa.py
It is required for CI pipelines to be run as a container.
Changes:
1. Added a Dockerfile
2. Made aws account file as optional, it can be replaced with local env vars
Test Command:
```
podman run --env ES_SERVER=https://search-perfscale-pro-wxrjvmobqs7gsyi3xvxkqmn7am.us-west-2.es.amazonaws.com:443 --env AWS_SECRET_ACCESS_KEY=<>  --env AWS_ACCESS_KEY_ID=<>  --env AWS_REGION=us-east-2  -it 503d9fd67291 python3 hcp-burner.py
```
- Closes #
> HCP burner to be executed as containers

- libs/platforms/platform.py
- libs/platforms/rosa/hypershift/hypershift.py
- libs/platforms/rosa/rosa.py
- libs/platforms/rosa/terraform/terraform.py
- libs/utils.py
Fixes #28 comment to move this metadata collection out of `utils.py`.
This has to go in before that PR.
- Closes #
> moved hypershift metadata collection in to respective class

- libs/platforms/azure/azure.py
- libs/platforms/azure/hypershiftcli/hypershiftcli.py
- Updated metadata function from #29 to hypershiftcli subplatform
- Enabled indexing during HCP creation
- Closes #
> included MC metrics indexing for HCP creation

- libs/platforms/azure/hypershiftcli/hypershiftcli.py
- libs/platforms/rosa/hypershift/hypershift.py
- libs/platforms/rosa/terraform/terraform.py
We are indexing data for every install at the time install finish, this is creating weird graphs on grafana.
Moving index timestamp to the start of the install/destroy process, creates better graphs, so you can easily see when the process is started just watching at the graph
- Closes #
> Create timestamp for indexing as the creation/deletion launch, not when finish

- libs/platforms/azure/hypershiftcli/hypershiftcli.py
- libs/platforms/platform.py
- Added controlplane ready timer
- Added total/delta timers for:
- Install_time: time to complete the hypershift install command
- Control Plane ready: time until OCP API is reachable
- Cluster Ready: time until HCP is reported as ready
- Workers Ready: time until all workers are ready
For every timer, now we **xx_total** for total time since `hypershift cluster create` is launched and **xx_delta0** for the time since the previous stage.
This is to make dashboard creation easier, following dashboard has been also modified to use new timers
Execution example: https://grafana.rdu2.scalelab.redhat.com:3000/d/tQHfAzyVz/managed-services-install-timings?orgId=1&from=now-12h&to=now&var-datasource=bDQe-DMVz&var-uuid=618d98e5-14c6-4bfa-b5f1-65732efe6d4f&var-install_method=All&var-mgmt_cluster_name= …
> Refactor azure hypershift install timers

- libs/platforms/azure/hypershiftcli/hypershiftcli.py
Detected failures on kubeconfig secret download on AKS, adding 5 minutes of retries on the kubeconfig downloading function
- Closes #
> Add retries to kubeconfig download on HCP Azure

- libs/platforms/azure/hypershiftcli/hypershiftcli.py
We were obtained the management cluster name from the context of the kubeconfig file, but this context has changed on the last version.
Adding as parameter, as getting on that way was not the perfect solution, and may introduce errors if it changes again in the future
- Closes #
> Add Azure MC name as parameter because of kubectl context

- libs/platforms/rosa/hypershift/hypershift.py
updated to use correct VPC count and made logic to reuse vpc continuously. 
first x clusters use the same VPC based on the given clusters_per_vpc argument.
- Closes #
> reuse vpc for multiple rosa  hcp

- Dockerfile
- libs/platforms/rosa/hypershift/hypershift.py
- libs/platforms/rosa/rosa.py
- Added `rosa create account-roles --hosted-cp  --prefix ManagedOpenShift -y --mode auto`
- Update rosa cli install command for containers
- Closes #
> rosa create account roles

- libs/platforms/azure/azure.py
- libs/platforms/azure/hypershiftcli/hypershiftcli.py
- libs/platforms/platform.py
- Disabled OCM token requirement for all the platforms, as hypershift do not need it
- Refactor on credentials so we can use original azure_credentials and dns_credentials files
- renamed default aks cluster name
- Closes #
> Requirements for new hypershift deployment v2

- docs/index.md
- Clarified how to convert CLI arguments to config file format (hyphen to underscore)
Clarified how to convert CLI arguments to config file format (hyphen to underscore), fixed the typo.
- Closes #
> Fix Readme: How to convert CLI arguments to config file

- libs/platforms/platform.py
- libs/utils.py
Replace 'ocm describe cluster <name>' with 'ocm list clusters' filtering by name to avoid ambiguity when multiple subscriptions exist with the same cluster name.
1) Fix subscription ambiguity issue:
The previous approach using 'ocm describe cluster <name>' would fail when
multiple subscriptions existed with the same cluster name (from previously
destroyed clusters), resulting in the error:
$ ocm describe cluster '<cluster name>'
Error: Can't retrieve cluster for key '<cluster name>':
There are 2 subscriptions with cluster identifier or name '<cluster name>'
The new approach uses 'ocm list clusters' which only shows active clusters,
avoiding conflicts with historical subscription records.
2) Fix subprocess argument handling:
After switching to the new command, subprocess was not handling …
> Use ocm list clusters for ID lookup

- libs/utils.py
- [] New feature
This enhancement to the cluster_load method ensures that all cluster
operators are stable before starting workload execution. It helps avoid
failures caused by attempting to run workloads while operators are still
initializing or stabilizing.
- Closes #
> Wait for co to get stable

- libs/arguments.py
- libs/utils.py
Allow the delay between cleaning up clusters to be set in seconds instead of minutes. Even 1 minute takes far to long to make this test effort at large scale repeatable.
> Allow the cleanup delay to be set in seconds instead of minutes

- utils/download_tools.sh
The rosa binary is now distributed as a `.tar.gz` archive instead of a raw binary.
Update the download script to fetch the correct asset, extract the `rosa` binary from the archive, and clean up.
> fix: Update rosa download script to handle rename and new tarball format

- libs/platforms/rosa/hypershift/hypershift.py
In the last scale test 8 clusters were missing kubeconfigs and upon further log analysis it was discovered that this error log line has a formatting issue that managed to hide its stack trace without killing the entire hcp-burner run. The missing clusters actually eventually succeeded in being created so we should extend the timeout for namespace creation in SC to 60 minutes.
- Closes #66
> Fix logging format error and adjust timeout for SC namespace to 60 minutes

- docs/aws_cleanup.md
- utils/vpc_cleanup.py
This commit introduces a new Python script, `vpc_cleanup.py`, for discovering and deleting AWS VPCs and their associated resources.
The script provides a command-line interface to:
- Find target VPCs by specific ID or by a substring in the 'Name' tag.
- Identify dependencies like Subnets, Security Groups, NACLs, and Gateways.
- Delete dependencies in the correct order before deleting the VPC.
- Operate in a safe, "find-only" mode by default.
- Simulate deletions with a `--dry-run` flag for safety.
A corresponding README.md is also added, which details prerequisites, usage instructions for all modes, and includes a critical warning about the script's limitations.
- Related Issue #52
> Introduce VPC cleanup script and documentation
